repo: 'responsive-image-caption'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - google-fonts
  - img-flex
  - css
  - border-box
  - responsive-css
  - responsive-font-sizes
  - body-margin-0
  - screenshots-all

html:
  - path: 'index.html'
    outline: false
    has:
      - ['link[href*="Denk+One"]', 'The webfont “Denk One” is missing']
      - ['img.img-flex[src$="dimetrodon.svg"]', 'The image of the Dimetrodon should have the class `.img-flex`']
      - 'h2'
      - 'p'
    search:
      - 'Dimetrodon'
      - 'Often mistaken for a dinosaur but went extinct 40 M years before dinosaurs.'

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'font', 'normal 100%/1.3 Georgia, serif']
    search:
      - 'position: relative'
      - 'position: absolute'
      - 'background-color: #e2e2e2;'
      - 'font-family: "Denk One", sans-serif;'
      - 'font-size: 1.5rem;'
      - 'background-color: rgba\(0, 0, 0, .3\)'
      - 'border-radius:'
